//states
#define VOLUME_MODE_STATE 0
#define ASSIST_MODE_STATE 1
#define IDLE_MODE_STATE 2
#define BUTTON_PRESSED    LOW
#define LIMIT_REACHED     LOW

#define DIRECTION_OPEN    HIGH
#define DIRECTION_CLOSE   LOW
